config/routes.rb
Rails.application.routes.draw do

  root "boards#top"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy]

  resources :boards do
    collection do
      get :favorite
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :content, presence: true, length: { in: 1..140 }

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :board
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :boards, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_boards, through: :favorites, source: :board
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  before_action :current_user_check, only: [:new, :edit, :show, :destroy]

  def top
  end

  def index
    @boards = Board.all
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    @board.user_id = current_user.id
    if @board.save
      CreateBoardMailer.create_board(@board).deliver
      redirect_to boards_path, notice: "さくせいしました"
    else
      render 'new'
    end
  end

  def show
    @favorite = current_user.favorites.find_by(board_id: @board.id)
  end

  def update
    if @board.update(board_params)
      redirect_to boards_path, notice: "へんしゅうしました"
    else
      render 'edit'
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path, notice: "けしました"
  end

  def favorite
    @favorites = current_user.favorite_boards
  end

  private
  def board_params
    params.require(:board).permit(:content, :created_at, :image)
  end

  def set_board
    @board = Board.find(params[:id])
  end

  def current_user_check
    current_user
    if !logged_in?
      redirect_to new_session_path, notice: "ログインしてください"
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(board_id: params[:board_id])
    redirect_to boards_url, notice: "#{favorite.board.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(board_id: params[:board_id]).destroy
    redirect_to boards_url, notice: "#{favorite.board.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      current_user
      redirect_to boards_path
    else
      flash[:danger] = "ログインに失敗しました"
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: @board, local: true) do |form| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= @board.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @board.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-area">
    <div>
      <%= form.label :ないよう %>
    </div>
    <div>
      <%= form.text_area :content %>
    </div>
    <div class="field">
      <%= form.label :がぞう %>
      <%= form.file_field :image, id: :board_image, class: 'field' %>
    </div>
    <div class="submit-button">
      <%= form.submit :ほぞん %>
    <div>
  </div>
    <%= link_to "もどる", boards_path %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>へんしゅう</h1>
<%= render 'form' %>

app/views/boards/favorite.html.erb
<h1>おきにいりいちらん</h1>
<% if @favorites.present? %>
  <div class="favorite-area">
    <% @favorites.each do |t| %>
      <p>なまえ: <%= t.user.name %>さん</p>
      <p>ないよう: <%= t.content %><p>
    <% end %>
  </div>
<% end %>

app/views/boards/index.html.erb
<div class="container jumbotron">
  <div class="header">
    <h3><%= notice %></>
      <h2>いちらん</h2>
      <h2><%= link_to 'かく', new_board_path %></h2>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-8">
      <div class="row">
        <% count = 0 %>
        <% @boards.each do |board| %>
        <% count += 1%>
        <div class="board_contents col-xs-12 col-md-8">
          <div class="contents">
            <%= "かいたひと:ID #{board.user_id}" %>  <%= link_to  board.content, board_path(board.id), class:"content" %>
          </div>
            <%= link_to 'へんしゅう', edit_board_path(board.id), class: 'btn btn-info'  %> |
            <%= link_to 'けす', board, method: :delete, data: { confirm: 'ほんとに?'}, class: 'btn btn-danger'  %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
      <div class="side-bar row">
        <div class="col-xs-12 col-md-offset-2 col-md-10">
          <h3>かいたかず</h3>
          <h3><%= count%>　こ</h3>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/boards/new.html.erb
<h2>さくせい</h2>
<%= render 'form' %>

app/views/boards/show.html.erb
<div class="show-area">

  <h1>詳細</h1>
  <p>内容: <%= @board.content %></p>
  <% if @board.image.present?%>
    <p>がぞう</p>
    <div><%= image_tag @board.image_url, class: 'image-area' %></div>
  <% end %>
  <div class="favorite-area">
    <% unless @board.user == current_user %>

      <% if @favorite.present? %>
        <%= link_to "お気に入りを解除する", favorite_path(board_id: @board.id), method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <%= link_to "お気に入りにする", favorites_path(board_id: @board.id ), method: :post, class: 'btn btn-primary' %>
      <% end %>
    <%= link_to "もどる", boards_path %>
    <% end %>
  </div>

</div>

app/views/boards/top.html.erb
<div class="jumbotron">
  <h1>とっぷがめん</h1>
  <h2><%= link_to "いちらんへ", boards_path%></h2>
  <div><img src="http://1.bp.blogspot.com/-TCt0mfD4bqQ/Vycehcr_tDI/AAAAAAAA6VA/0XsMlRl_PUAg5C-zFTlVyTyM3pmeLlSgQCLcB/s800/tegami_bird.png" class="img-responsive"></div>
  <h2>なにかかいてほぞんしてください</h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterCopyApp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul>
        <li><img src="http://1.bp.blogspot.com/-TCt0mfD4bqQ/Vycehcr_tDI/AAAAAAAA6VA/0XsMlRl_PUAg5C-zFTlVyTyM3pmeLlSgQCLcB/s800/tegami_bird.png" alt="" width="30px" height="30px"></li>
        <li><%= link_to "ぶろぐ",boards_path %></li>
        <li><%= link_to "おきにいり", favorite_boards_path %></li>
      </ul>
    </header>

    <% flash.each do |key, value| %>
      <% content_tag(:div, value, class: "#{key}") %>
    <% end %>

      <% if logged_in? %>
        <%= link_to "プロフィール", user_path(current_user.id) %>
        <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
        <%= "あなたのID：#{current_user.id}" %>
      <% else %>
        <%= link_to "しんきとうろく", new_user_path %>
        <%= link_to "ログイン", new_session_path %>
      <% end %>

    <%= yield %>

    <footer>ryota_k</footer>
  </body>
</html>

app/views/users/new.html.erb
<h1>とうろく</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <table>
    <tr>
      <td><%= f.label :なまえ %></td>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td><%= f.label :メール %></td>
      <td><%= f.email_field :email %></td>
    </tr>
    <tr>
      <td><%= f.label :パスワード %></td>
      <td><%= f.password_field :password %></td>
    </tr>
    <tr>
      <td><%= f.label :パスワードかくにん %></td>
      <td><%= f.password_field :password_confirmation %></td>
    </tr>
    <tr class="field">
      <td><%= f.label :がぞう %></td>
      <td><%= f.file_field :image, id: :user_image %></td>
    </tr>
  </table>

    <div class="user_btn"><%= f.submit "とうろく" %></div>
<% end %>

app/views/users/show.html.erb
<div class="show-area">
  <%= form_with(model: @user, local: true) do |form| %>
    <h1><%= @user.name %>のページ</h1>

    <p class="user_p">メールアドレス: <%= @user.email %></p>
    <% if @user.image.present? %>
      <div><%= image_tag @user.image_url, class: 'image-area' %></div>
      <div class="user_btn"><%= link_to "いちらんへ", boards_path%></div>
    <% end %>
  <% end %>
</div>